GENOMIC_PROJECTION = {
    "TIER": 1,
    "VARIANT_CATEGORY": 1,
    "WILDTYPE": 1,
    "TRUE_HUGO_SYMBOL": 1,
    "TRUE_PROTEIN_CHANGE": 1,
    "CNV_CALL": 1,
    "TRUE_VARIANT_CLASSIFICATION": 1,
    "MMR_STATUS": 1,
    'SAMPLE_ID': 1,
    'CHROMOSOME': 1,
    'POSITION': 1,
    'TRUE_CDNA_CHANGE': 1,
    'REFERENCE_ALLELE': 1,
    'TRUE_TRANSCRIPT_EXON': 1,
    'CANONICAL_STRAND': 1,
    'ALLELE_FRACTION': 1,
    'CLINICAL_ID': 1,
    'ACTIONABILITY': 1,
    'STRUCTURAL_VARIANT_COMMENT': 1
}

CLINICAL_PROJECTION = {
    "SAMPLE_ID": 1,
    'MRN': 1,
    "CHROMOSOME": 1,
    'ORD_PHYSICIAN_NAME': 1,
    'ORD_PHYSICIAN_EMAIL': 1,
    'ONCOTREE_PRIMARY_DIAGNOSIS_NAME': 1,
    'REPORT_DATE': 1,
    'VITAL_STATUS': 1,
    'FIRST_LAST': 1,
    'GENDER': 1

}